#!/bin/bash

clear

printmenu(){

clear
echo -e "
1.Launch Winedesktop
2.Launch Windesktop with OldLoader(Devices with Black Screen)
3.CLI Launcher(only useful when debug log are not complete)
4.Troubleshooting
5.Tweaks
6.Update
7.Quit
"

}

troubleshootingmenu(){

clear
cat << EOF
1.Rebuild prefix
2.Kill wine
3.Switch to new Termux:X11 loader
4.Reinstall glibc prefix
5.Reinstall wine

EOF


}

tweaksmenu(){

clear
cat << EOF
1.Install a winetricks verb

EOF

}


oldloader(){

export CLASSPATH=/data/data/com.termux/files/usr/glibc/loader.apk
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process / com.termux.x11.Loader >/dev/null 2>&1 &

}

getcommitmessage(){

cd $HOME
git clone --filter=blob:none --no-checkout --single-branch --branch androBoxNew https://github.com/Pipetto-crypto/androBox.git >/dev/null 2>&1
cd androBox
log="$(git log -n 1 --pretty=format:%B -- $1 | cut -d':' -f2-)"
rm -rf $HOME/androBox
echo "$log"

}

apply_last_patch(){

echo -e "\nChecking for available patches..."
lastavailablepatch="$(curl -sL https://github.com/Pipetto-crypto/androBox/raw/androBoxNew/patches/patch.tar.xz | sha1sum | awk '{print $1}')"
lastinstalledpatch="$(cat /sdcard/androBox/.patch1sum)"
isonline="$(ping -w1 -q -c1 google.com &>/dev/null && echo $?)"

if [ "$lastavailablepatch" == "$lastinstalledpatch" ]
then
     echo -e "\nLast patch is already installed."
elif [ "$isonline" == "0" ]
then
     printf "\nYou are downloading a new patch which commit message is:%s\n" "$(getcommitmessage patches)"
     echo -e "\nInstalling last patch..."
     apply_patch >/dev/null 2>&1
     echo -e "\nLast patch installed."
else
     echo -e "\nI am not capable of find any new patch online, enable your Internet connection next time."
fi

}

update_scripts(){

isonline="$(ping -w1 -q -c1 google.com &>/dev/null && echo $?)"
echo -e "\nChecking for available scripts update..."
touch /sdcard/androBox/.lastupdated
lastavailablecommit="$(git ls-remote --heads https://github.com/Pipetto-crypto/androBox.git | grep refs/heads/androBoxNew | awk '{print $1}')"
lastinstalledcommit="$(cat /sdcard/androBox/.lastupdated | head -n1)"
lastinstalledcommitmessage="$(cat /sdcard/androBox/.lastupdated | tail -n1)"
lastavailablecommitmessage="$(getcommitmessage scripts)"

if [ "$isonline" == "0" ]
then
     if [ "$lastavailablecommit" == "$lastinstalledcommit" ] || [[ "$lastavailablecommitmessage" =~ "$lastinstalledcommitmessage" ]]
     then
          echo -e "\nNo new updates found."
     else
          printf "\nYou are downloading an update to scripts which commit message is:%s\n" "$(getcommitmessage scripts)"
          echo -e "\nInstalling new updates..."
          source update-scripts >/dev/null 2>&1
          echo -e "\nNew updates installed"
          echo "$lastavailablecommitmessage" >> /sdcard/androBox/.lastupdated
     fi
else
     echo -e "\nI am not capable of finding any new update, enable your Internet connection next time."
fi


}

update_androbox(){

isonline="$(ping -w1 -q -c1 google.com &>/dev/null && echo $?)"
if [ "$isonline" == "0" ]
then 
     remotesum="$(curl -sL https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/androBox | sha1sum | awk '{print $1}')"
     localsum="$(sha1sum $PATH/androBox | awk '{print $1}')"
     if [ "$remotesum" != "$localsum" ]
     then
          printf "\nYou are downloading an update to androBox which commit message is:%s\n" "$(getcommitmessage androBox)"
          echo -e "\nInstalling new androBox update, remember to relaunch after update is done..."   
          wget -q https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/androBox -P $HOME
          mv $HOME/androBox $PATH
          chmod +x $PATH/androBox
          exit
     else
          rm -rf $HOME/androBox
     fi
fi

}

startservers(){

[[ -z $(pidof pulseaudio) ]] && pulseaudio --start --exit-idle-time=-1 && pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
termux-x11 >/dev/null 2>&1 &
sleep 2

}



startdesktop(){

echo -e "\nTrying to apply correct resolution, the desktop will restart multiple times until correct resolution is applied..."

sleep 3

export screenres="$(xrandr | grep current | awk '{print $8$9$10}' | tr -d ,)"
[[ -z $(grep -w "checkres=disabled" $HOME/.androBox) ]] && [[ -z $(ps -aux | grep "[w]atch" | awk '{print $2}') ]] && $PREFIX/glibc/opt/WinScripts/checkres.sh &

echo -e "\nLaunching..."

sleep 2

am start -n com.termux.x11/com.termux.x11.MainActivity >/dev/null 2>&1
winedesktop >/dev/null 2>&1 &

}

startoldloader(){

kill $(pidof app_process)
oldloader
sleep 2

}


setvars(){

GLIBC_PREFIX=/data/data/com.termux/files/usr/glibc

cat > $TMPDIR/.myvars <<- EOM
#!/data/data/com.termux/files/usr/bin/bash

export VK_ICD_FILENAMES=$GLIBC_PREFIX/share/vulkan/icd.d/freedreno_icd.aarch64.json:$GLIBC_PREFIX/share/vulkan/icd.d/freedreno_icd.armhf.json
export LIBGL_DRIVERS_PATH=$GLIBC_PREFIX/lib/dri:$GLIBC_PREFIX/lib32/dri
export DISPLAY=:0
export USE_HEAP=1
export TU_DEBUG=noconform
export MESA_LOADER_DRIVER_OVERRIDE=zink
export FONTCONFIG_PATH=$PREFIX/etc/fonts
export PULSE_SERVER=127.0.0.1
EOM

source $TMPDIR/.myvars

}

killwine(){

$PREFIX/glibc/opt/WinScripts/exit.sh

}

reinstallglibcprefix(){

rm -rf /sdcard/glibc_prefix.tar.xz && rm -rf $PREFIX/glibc
wget https://github.com/Pipetto-crypto/androBox/releases/download/glibc_prefix/glibc_prefix.tar.xz -P /sdcard
tar -xf /sdcard/glibc_prefix.tar.xz -C $PREFIX

}

reinstallwine(){

rm -rf /sdcard/wine-8.14-amd64.tar.xz && rm -rf $PREFIX/glibc/opt/wine
if [ ! -f $HOME/.local/cache/wine-8.14-amd64.tar.xz ]
then
     wget https://github.com/Pipetto-crypto/androBox/releases/download/wine/wine-8.14-amd64.tar.xz -P /sdcard
     tar -xf /sdcard/wine-8.14-amd64.tar.xz -C $PREFIX/glibc/opt && mv $PREFIX/glibc/opt/wine-8.14-amd64  $PREFIX/glibc/opt/wine
else
     tar -xf $HOME/.local/cache/wine-8.14-amd64.tar.xz -C $PREFIX/glibc/opt && mv $PREFIX/glibc/opt/wine-8.14-amd64  $PREFIX/glibc/opt/wine
fi

}

killonexit(){

kill $(pidof app_process)
pkill pulseaudio
killwine

}

uninstall(){

rm -rf $PREFIX/glibc
rm -rf Configurator.py install_dxvk remove_dxwrapper install_dxvk_async remove_wined3d install_dxvk_gplasync startup.bat install_dxwrapper update-scripts apply_patch install_wined3d wine box64switch mesaswitch winedesktop box86switch pfxupdate winetricks install_d3d8to9 remove_d8vk winetricks_x86 install_d8vk remove_dxvk androBox
exit

}

case "$1" in
--uninstall)
     uninstall
     ;;
-nc)
     echo -e "Skipping updates checking"
     ;;
*)
     update_androbox
     update_scripts
     apply_last_patch
     ;;
esac

startservers
setvars

code=""

while [ True ]
do 
   printmenu
   read -p "Select an operation: " code
   case $code in 
   1)
       killwine
       startdesktop
       ;;
   2)
       killwine
       startoldloader
       startdesktop
       ;;
   3)
       killwine
       file=$(nnn -p - $HOME/.wine)
       wine $file &
       ;;
   4)
       troubleshootingmenu
       read -p "Select an option: " tbshmenu
       case $tbshmenu in
       1)
          killwine
          rm -rf $HOME/.wine
          WINEDLLOVERRIDES="mscoree=" wine wineboot
          pfxupdate
          user="$(ls $HOME/.wine/drive_c/users | grep -e '^u')"
          mkdir -p $HOME/.wine/drive_c/users/$user/AppData/Local/ProcessLasso/config
          cp -r $PREFIX/glibc/opt/Programs/ProcessLasso/prolasso.ini $HOME/.wine/drive_c/users/u*/AppData/Local/ProcessLasso/config
          ;;
       2)
          killwine
          ;;
       3)
          pkg install --reinstall termux-x11-nightly -y >/dev/null 2>&1
          ;;
       4)
          killwine
          reinstallglibcprefix
          ;;
       5)
          killwine
          reinstallwine
          ;;
       esac
       ;;
   5)
       tweaksmenu
       read -p "Select an option: " twkopt
       case $twkopt in
       1)
          read -p "Type the name of a winetrick verb you want to install: " tweak
          printf "\nI will install %s verb...\n" "$tweak"
          winetricks $tweak -f
          ;;
       esac
       ;;
   6)
       echo -e "\nInstalling new androBox update, remember to relaunch after update is done..."
       wget -q https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/androBox -P $HOME
       mv $HOME/androBox $PATH
       chmod +x $PATH/androBox
       exit
       ;;
   7)
       killonexit
       exit
       ;;
   esac
done
