#!/data/data/com.termux/files/usr/bin/bash

wget https://github.com/Pipetto-crypto/androBox/raw/androBoxNew/patches/patch.tar.xz -P $HOME
tar -xf ~/patch.tar.xz -C $HOME
bash ~/patch/execute-patch.sh

