#!/bin/bash

version=$1
month=$2
cachedir="$HOME/.local/cache"
mkdir -p $cachedir

apt remove --purge box64-android -y

if [ ! -f $cachedir/box64_"$version"_"$month"_arm64.deb ]
then
     wget https://github.com/Pipetto-crypto/box86_box64_debs/raw/master/box64debs/box64_"$version"_"$month"_arm64.deb -P $cachedir
fi
yes | dpkg -i $cachedir/box64_"$version"_"$month"_arm64.deb
apt-mark hold box64
