#!/bin/bash

VERSION="$(cat ~/.config/exawineconf | awk 'NR==1')"
WINEDLLOVERRIDES="$(cat ~/.config/exawineconf | awk 'NR==2')"
ARCH=x86

index=1
for var in "$@"
do
   if [ -f "$var" ]
   then
        absfile=$(realpath -e "$var")
        argslist[$index]="$absfile"
   elif [ "$var" == "-nodxvk" ]
   then
        WINEDLLOVERRIDES=""
   elif [ "$var" == "-winedbg" ]
   then
        WINEDEBUG="default"
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done

env WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix/wine-$VERSION} \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
WINEDEBUG=${WINEDEBUG:=-all} \
exagear -- $HOME/wine-$VERSION-$ARCH/bin/wine "${argslist[@]}"

