#!/bin/bash



index=1
for var in "$@"
do
   if [ -f $var ]
   then
        absfile=$(realpath -e $var)
        argslist[$index]="$absfile"
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done

VERSION=7.1
ARCH=x86
env WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix/wine-$VERSION} \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
exagear -- $HOME/wine-$VERSION-$ARCH/bin/wine "${argslist[@]}"

