#!/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH
ARCH=$(cat ~/.wine/system.reg | grep arch= | cut -f2- -d"=")
PREFIX=$HOME/.wine


dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> $input
echo "[Software\\\Wine\\\DllOverrides]" >> $input
echo "" >> $input
echo "\"$dlltoverride"\""=""\"$type"\" >> $input

}

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/d3d8.dll ]
then
     wget https://github.com/crosire/d3d8to9/releases/download/v1.11.1/d3d8.dll -P $cachedir
fi

if [ "$ARCH" == "win32" ]
then
     cp -r $cachedir/d3d8.dll $PREFIX/drive_c/windows/system32
else
     cp -r $cachedir/d3d8.dll $PREFIX/drive_c/windows/syswow64
fi
if [ "$1" == "-partial" ];then exit;fi
dlloverride $PREFIX d3d8 native,builtin




