#!/bin/bash

WINEVERSION="$(cat ~/.config/wineconf | awk 'NR==1')"
CURRARCH="$(cat ~/.config/wineconf | awk 'NR==2')"
if [ "$CURRARCH" == "32" ];then CURRARCH="";fi
PREFIX=$HOME/.local/wineprefix$CURRARCH/wine-$WINEVERSION

dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> $input
echo "[Software\\\Wine\\\DllOverrides]" >> $input
echo "" >> $input
echo "\"$dlltoverride"\""=""\"$type"\" >> $input

}

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/d3d8.dll ]
then
     wget https://github.com/crosire/d3d8to9/releases/download/v1.11.1/d3d8.dll -P $cachedir
fi

if [ "$CURRARCH" == "" ]
then
     cp -r $cachedir/d3d8.dll $PREFIX/drive_c/windows/system32
else
     cp -r $cachedir/d3d8.dll $PREFIX/drive_c/windows/syswow64
fi
if [ "$1" == "-partial" ];then exit;fi
dlloverride $PREFIX d3d8 native,builtin




