#!/bin/bash

WINEVERSION="$(cat ~/.config/wineconf | awk 'NR==1')"
CURRARCH="$(cat ~/.config/wineconf | awk 'NR==2')"
if [ "$CURRARCH" == "32" ];then CURRARCH="";fi
PREFIX=$HOME/.local/wineprefix$CURRARCH/wine-$WINEVERSION

dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> "$input"
echo "[Software\\\Wine\\\DllOverrides]" >> "$input"
echo "" >> "$input"
echo "\"$dlltoverride"\""=""\"$type"\" >> "$input"

}

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/d8vk-v1.0.tar.gz ]
then
     wget https://github.com/AlpyneDreams/d8vk/releases/download/d8vk-v1.0/d8vk-v1.0.tar.gz -P $cachedir
fi
mkdir -p ~/d8vk
tar -xzf $cachedir/d8vk-v1.0.tar.gz -C ~/d8vk


if [ "$CURRARCH" == "" ]
then
     cp -r ~/d8vk/x32/* $PREFIX/drive_c/windows/system32
else
     cp -r ~/d8vk/x32/* $PREFIX/drive_c/windows/syswow64
fi
if [ "$1" == "-partial" ];then rm -rf ~/d8vk && exit;fi
dlloverride $PREFIX d3d8 native,builtin


rm -rf ~/d8vk 
