#!/bin/bash

WINEVERSION="$(cat ~/.config/wine64conf | awk 'NR==1')"
WINEVERSION32="$(cat ~/.config/wineconf | awk 'NR==1')"
EXAWINEVERSION="$(cat ~/.config/exawineconf | awk 'NR==1')"
WINEPREFIX64=$HOME/.local/wineprefix64/wine-$WINEVERSION
WINEPREFIX32=$HOME/.local/wineprefix/wine-$WINEVERSION32
EXAWINEPREFIX=$HOME/.local/wineprefix/wine-$EXAWINEVERSION
GEPREFIX=$HOME/.local/wineprefix64/lutris-GE-Proton8-5

dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> "$input"
echo "[Software\\\Wine\\\DllOverrides]" >> "$input"
echo "" >> "$input"
echo "\"$dlltoverride"\""=""\"$type"\" >> "$input"

}

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/d8vk-v1.0.tar.gz ]
then
     wget https://github.com/AlpyneDreams/d8vk/releases/download/d8vk-v1.0/d8vk-v1.0.tar.gz -P $cachedir
fi
mkdir -p ~/d8vk
tar -xzf $cachedir/d8vk-v1.0.tar.gz -C ~/d8vk

choices=()
if [ "$1" != "" ]
then
     choices+=$1
else
     echo -e "\nSelect where to install: "
     echo -e "1.Wine"
     echo -e "2.Exawine"
     echo -e "3.Wine64"
     echo -e "4.WineGE"

     while [ True ]
     do
        read -p "Your choice, press q to break and enter to confirm: " CHOICE
        if [ "$CHOICE" == "q" ];then break;fi
        choices+=($CHOICE)
     done
fi


if [[ "${choices[*]}" =~ "3" ]]
then
     cp -r ~/d8vk/x32/* $WINEPREFIX64/drive_c/windows/syswow64
     if [ "$2" == "-partial" ];then rm -rf ~/d8vk && exit;fi
     dlloverride $WINEPREFIX64 d3d8 native,builtin
     
elif [[ "${choices[*]}" =~ "1" ]]
then
     cp -r ~/d8vk/x32/* $WINEPREFIX32/drive_c/windows/system32
     if [ "$2" == "-partial" ];then rm -rf ~/d8vk && exit;fi
     dlloverride $WINEPREFIX32 d3d8 native,builtin
else
     cp -r ~/d8vk/x32/* $GEPREFIX/drive_c/windows/syswow64
     if [ "$2" == "-partial" ];then rm -rf ~/d8vk && exit;fi
     dlloverride $GEPREFIX d3d8 native,builtin
fi



rm -rf ~/d8vk 
