#!/bin/bash

WINEVERSION="$(cat ~/.config/wineconf | awk 'NR==1')"
CURRARCH="$(cat ~/.config/wineconf | awk 'NR==2')"
if [ "$CURRARCH" == "32" ];then CURRARCH="";fi
PREFIX=$HOME/.local/wineprefix$CURRARCH/wine-$WINEVERSION

dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> "$input"
echo "[Software\\\Wine\\\DllOverrides]" >> "$input"
echo "" >> "$input"
echo "\"$dlltoverride"\""=""\"$type"\" >> "$input"

}

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/dxwrapper.zip ]
then
      wget https://github.com/elishacloud/dxwrapper/releases/download/v1.0.6542.21/dxwrapper.zip -P $cachedir
fi
unzip -d ~/dxwrapper $cachedir/dxwrapper.zip
linenumber="$(awk '/Dd7to9/{print NR}' ~/dxwrapper/dxwrapper.ini | head -n 1)"
sed -i "$linenumber""s/=.*/=1/g" ~/dxwrapper/dxwrapper.ini



if [ "$CURRARCH" == "" ]
then
     cp -r ~/dxwrapper/Stub/ddraw.dll ~/dxwrapper/dxwrapper.dll ~/dxwrapper/dxwrapper.ini $PREFIX/drive_c/windows/system32
else
     cp -r ~/dxwrapper/Stub/ddraw.dll ~/dxwrapper/dxwrapper.dll ~/dxwrapper/dxwrapper.ini $PREFIX/drive_c/windows/syswow64
fi     
if [ "$1" == "-partial" ];then rm -rf ~/dxwrapper && exit;fi
dlloverride $PREFIX ddraw native,builtin

rm -rf ~/dxwrapper
