#!/data/data/com.termux/files/usr/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH
ARCH=$(cat ~/.wine/system.reg | grep arch= | cut -f2- -d"=")
PREFIX=$HOME/.wine


dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> $input
echo "[Software\\\Wine\\\DllOverrides]" >> $input
echo "" >> $input
echo "\"$dlltoverride"\""=""\"$type"\" >> $input

}

if [ "$1" != "" ]
then
     DXVKVER="$1"
else
     read -p "Select a DXVK version to install:" DXVKVER
fi


cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/dxvk-gplasync-v$DXVKVER.tar.gz ]
then
     wget https://gitlab.com/Ph42oN/dxvk-gplasync/-/raw/main/releases/dxvk-gplasync-v$DXVKVER.tar.gz -P $cachedir
fi
tar -xzf $cachedir/dxvk-gplasync-v$DXVKVER.tar.gz -C ~

     

if [ "$ARCH" == "win32" ]
then
     cp ~/dxvk-gplasync-v$DXVKVER/x32/* $PREFIX/drive_c/windows/system32
else
     cp ~/dxvk-gplasync-v$DXVKVER/x32/* $PREFIX/drive_c/windows/syswow64
     cp ~/dxvk-gplasync-v$DXVKVER/x64/* $PREFIX/drive_c/windows/system32
fi
if [ "$2" == "-partial" ];then rm -rf ~/dxvk-gplasync-v$DXVKVER && exit;fi
   if (( $(echo "$(echo $DXVKVER | cut -f1,2 -d '.') > 1.10" | bc -l) ))
   then
        dlloverride $PREFIX dxgi native,builtin
        dlloverride $PREFIX d3d9 native,builtin
        dlloverride $PREFIX d3d11 native,builtin
        dlloverride $PREFIX d3d10core native,builtin
    else
        dlloverride $PREFIX dxgi native,builtin
        dlloverride $PREFIX d3d9 native,builtin
        dlloverride $PREFIX d3d11 native,builtin
        dlloverride $PREFIX d3d10 native,builtin
        dlloverride $PREFIX d3d10_1 native,builtin
     fi
fi

rm -rf ~/dxvk-async-$DXVKVER 
