#!/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH
ARCH=$(cat ~/.wine/system.reg | grep arch= | cut -f2- -d"=")
PREFIX=$HOME/.wine


dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> $input
echo "[Software\\\Wine\\\DllOverrides]" >> $input
echo "" >> $input
echo "\"$dlltoverride"\""=""\"$type"\" >> $input

}


if [ "$1" != "" ]
then
     wined3dver=$1
else
     read -p "Select a version of WINED3D to install:" wined3dver
fi

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/WineD3DForWindows_$wined3dver.zip ]
then
     wget https://downloads.fdossena.com/Projects/WineD3D/Builds/WineD3DForWindows_$wined3dver.zip -P $cachedir
fi
mkdir -p ~/wined3d
unzip $cachedir/WineD3DForWindows_$wined3dver.zip -d ~/wined3d
rm -rf ~/wined3d/ddraw.dll ~/wined3d/libwine.dll ~/wined3d/*.txt ~/wined3d/wined3d.dll

if [ "$ARCH" == "win32" ]
then
     cp -r ~/wined3d/* $PREFIX/drive_c/windows/system32
else
     cp -r ~/wined3d/* $PREFIX/drive_c/windows/syswow64
fi
if [ "$2" == "-partial" ];then rm -rf ~/wined3d && exit;fi
dlloverride $PREFIX d3d8 native,builtin
dlloverride $PREFIX d3d9 native,builtin
dlloverride $PREFIX d3d10core native,builtin
dlloverride $PREFIX d3d10 native,builtin
dlloverride $PREFIX d3d10_1 native,builtin
dlloverride $PREFIX d3d11 native,builtin
dlloverride $PREFIX dxgi native,builtin


rm -rf ~/wined3d 
 
