#!/data/data/com.termux/files/usr/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH
ARCH=$(cat ~/.wine/system.reg | grep arch= | cut -f2- -d"=")
PREFIX=$HOME/.wine

dlloverride(){

input="$1/user.reg"
dlltoverride="$2"
type="$3"
echo "" >> "$input"
echo "[Software\\\Wine\\\DllOverrides]" >> "$input"
echo "" >> "$input"
echo "\"$dlltoverride"\""=""\"$type"\" >> "$input"

}

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/d8vk-v1.0.tar.gz ]
then
     wget https://github.com/AlpyneDreams/d8vk/releases/download/d8vk-v1.0/d8vk-v1.0.tar.gz -P $cachedir
fi
mkdir -p ~/d8vk
tar -xzf $cachedir/d8vk-v1.0.tar.gz -C ~/d8vk


if [ "$ARCH" == "win32" ]
then
     cp -r ~/d8vk/x32/* $PREFIX/drive_c/windows/system32
else
     cp -r ~/d8vk/x32/* $PREFIX/drive_c/windows/syswow64
fi
if [ "$1" == "-partial" ];then rm -rf ~/d8vk && exit;fi
dlloverride $PREFIX d3d8 native,builtin


rm -rf ~/d8vk 
