#!/bin/bash

GEVERSION=8-5

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ ! -f $cachedir/wine-lutris-GE-Proton$GEVERSION-x86_64.tar.xz ]
then
     wget https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton$GEVERSION/wine-lutris-GE-Proton$GEVERSION-x86_64.tar.xz  -P $cachedir
fi

tar -xf $cachedir/wine-lutris-GE-Proton$GEVERSION-x86_64.tar.xz -C ~
winege winecfg
pfxupdate


