#!/data/data/com.termux/files/usr/bin/bash

arch=$1
type=$2
date=$3
revision=$4

cachedir="$HOME/.local/cache"
mkdir -p $cachedir/mesa/aarch64/turnip
mkdir -p $cachedir/mesa/aarch64/zink
mkdir -p $cachedir/mesa/armhf/turnip
mkdir -p $cachedir/mesa/armhf/zink

[[ ! -f ${cachedir}/mesa/${arch}/${type}/${type}_${date}${revision}.tar.xz ]] && wget https://github.com/Pipetto-crypto/mesa-builds/raw/master/${arch}/${type}/${type}_${date}${revision}.tar.xz -P ${cachedir}/mesa/${arch}/${type}

if [ $arch == "armhf" ]
then
     tar -xf ${cachedir}/mesa/${arch}/${type}/${type}_${date}${revision}.tar.xz -C $PREFIX/glibc/lib32
else
     tar -xf ${cachedir}/mesa/${arch}/${type}/${type}_${date}${revision}.tar.xz -C $PREFIX/glibc/lib
fi
