#!/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH

cleanmenu(){

path=$(dirname -- "$1")
cp -r "$1" $path/tmp
rm -rf "$1"
mkdir -p "$1"
mv $path/tmp/Programs "$1"
rm -rf $path/tmp

}

pfx=$HOME/.wine

cleanmenu "$pfx/drive_c/ProgramData/Microsoft/Windows/Start Menu"
cp -r $PREFIX/glibc/opt/WinStartMenu/* "$pfx/drive_c/ProgramData/Microsoft/Windows/Start Menu"
if [ ! -L "$pfx/dosdevices/e:" ];then ln -sf /sdcard "$pfx/dosdevices/e:";fi
if [ ! -L "$pfx/dosdevices/f:" ];then ln -sf $PREFIX/glibc/opt/Programs "$pfx/dosdevices/f:";fi
if [ ! -L "$pfx/dosdevices/t:" ];then ln -sf ~/.local/cache "$pfx/dosdevices/t:";fi
   
