#!/bin/bash

cleanmenu(){

path=$(dirname -- "$1")
cp -r "$1" $path/tmp
rm -rf "$1"
mkdir -p "$1"
mv $path/tmp/Programs "$1"
rm -rf $path/tmp

}

if [ ! -z "$(ls -A $HOME/.local/wineprefix)" ]
then
     for pfx in $HOME/.local/wineprefix/*
     do
        cleanmenu "$pfx/drive_c/ProgramData/Microsoft/Windows/Start Menu"
        cp -r /opt/WinStartMenu/* "$pfx/drive_c/ProgramData/Microsoft/Windows/Start Menu"
        if [ ! -L "$pfx/dosdevices/e:" ];then ln -sf /sdcard "$pfx/dosdevices/e:";fi
     done
fi

if [ ! -z "$(ls -A $HOME/.local/wineprefix64)" ]
then
     for pfx64 in $HOME/.local/wineprefix64/*
     do
        if [[ "$pfx64" =~ "lutris" ]]
        then
             cleanmenu "$pfx64/drive_c/ProgramData/Microsoft/Windows/Start Menu" 
             cp -r /opt/WinGEStartMenu/* "$pfx64/drive_c/ProgramData/Microsoft/Windows/Start Menu"
        else
             cleanmenu "$pfx64/drive_c/ProgramData/Microsoft/Windows/Start Menu"
             cp -r /opt/Win64StartMenu/* "$pfx64/drive_c/ProgramData/Microsoft/Windows/Start Menu"
        fi
        if [ ! -L "$pfx64/dosdevices/e:" ];then ln -sf /sdcard "$pfx64/dosdevices/e:";fi
     done
fi
