#!/bin/bash

copydll(){

local winarch=$(awk -F "=" /arch/'{print $2}' $WINEPREFIX/user.reg | head -n1)


local wineins="$(basename $WINEPREFIX)"                                                                               
local dlltocopy="d3d8"
local winedir=$HOME/$wineins-amd64
if [ -d $winedir/lib/wine/fakedlls ]
then
     if [ "$winarch" == "win32" ]
     then
          cp $winedir/lib/wine/$dlltocopy.* $WINEPREFIX/drive_c/windows/system32/$dlltocopy.dll
     else
          cp $winedir/lib/wine/$dlltocopy.* $WINEPREFIX/drive_c/windows/syswow64/$dlltocopy.dll
     fi   
else
     if [ "$winarch" == "win32" ]
     then
          cp $winedir/lib/wine/i386-windows/$dlltocopy.dll $WINEPREFIX/drive_c/windows/system32
     else
          cp $winedir/lib/wine/i386-windows/$dlltocopy.dll $WINEPREFIX/drive_c/windows/syswow64
     fi
fi


}

if [ "$WINEPREFIX" != "" ]
then
     copydll
fi
