#!/bin/bash

if [ "$SUDO_USER" != "" ];then HOME=/home/$SUDO_USER;fi
if [ ! "$(id -u)" = "0" ]
then
     echo -e "\nThis program needs to be ran with sudo"
fi

[[ ! -z $(awk 'FNR==3' /usr/bin/wine64) ]] && sed -i '3d' /usr/bin/wine64
[[ ! -z $(awk 'FNR==3' /usr/bin/wine) ]] && sed -i '3d' /usr/bin/wine
[[ ! -z $(awk 'FNR==3' /usr/bin/winege) ]] && sed -i '3d' /usr/bin/winege
wine64 wineboot -u
wine wineboot -u
winege wineboot -u
