#!/data/data/com.termux/files/usr/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH

copydll(){

local winarch=$(awk -F "=" /arch/'{print $2}' $WINEPREFIX/user.reg | head -n1)
local dlltocopy="ddraw"
local glibc_prefix=$PREFIX/glibc
local winever=$(wine --version | tail -n1 | cut -f2- -d"-")
local winedir=$glibc_prefix/opt/wine-$winever-amd64

if [ -d $winedir/lib/wine/fakedlls ]
then
     if [ "$winarch" == "win32" ]
     then
          cp $winedir/lib/wine/$dlltocopy.* $WINEPREFIX/drive_c/windows/system32/$dlltocopy.dll
     else
          cp $winedir/lib/wine/$dlltocopy.* $WINEPREFIX/drive_c/windows/syswow64/$dlltocopy.dll
     fi
else
     if [ "$winarch" == "win32" ]
     then
          cp $winedir/lib/wine/i386-windows/$dlltocopy.dll $WINEPREFIX/drive_c/windows/system32
     else
          cp $winedir/lib/wine/i386-windows/$dlltocopy.dll $WINEPREFIX/drive_c/windows/syswow64
          
     fi
fi


}

if [ "$WINEPREFIX" != "" ]
then
     copydll
fi
