#!/bin/bash

[[ ! -z $(awk 'FNR==3' /usr/bin/wine64) ]] && sed -i '3d' /usr/bin/wine64
[[ ! -z $(awk 'FNR==3' /usr/bin/wine) ]] && sed -i '3d' /usr/bin/wine
[[ ! -z $(awk 'FNR==3' /usr/bin/winege) ]] && sed -i '3d' /usr/bin/winege
wine64 wineboot -u
wine wineboot -u
winege wineboot -u
