#!/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH

copydll(){

local winarch=$(awk -F "=" /arch/'{print $2}' $WINEPREFIX/user.reg | head -n1)
local dlltocopy=("dxgi" "d3d8" "d3d9" "d3d10core" "d3d10" "d3d10_1" "d3d11")
local glibc_prefix=$PREFIX/glibc
local winever=$(wine --version | tail -n1 | cut -f2- -d"-")
local winedir=$glibc_prefix/opt/wine-$winever-amd64

if [ -d $winedir/lib/wine/fakedlls ] || [ -d $winedir/lib64/wine/fakedlls ]
then                                                                                                                       
     for dll in "${dlltocopy[@]}"
     do
        if [ "$winarch" == "win32" ]
        then
             cp $winedir/lib/wine/$dll.* $WINEPREFIX/drive_c/windows/system32/$dll.dll
        else
             cp $winedir/lib/wine/$dll.* $WINEPREFIX/drive_c/windows/syswow64/$dll.dll
             cp $winedir/lib64/wine/$dll.* $WINEPREFIX/drive_c/windows/system32/$dll.dll
        fi
     done
else
     for dll in "${dlltocopy[@]}"
     do
        if [ "$winarch" == "win32" ]
        then
             cp $winedir/lib/wine/i386-windows/$dll.dll $WINEPREFIX/drive_c/windows/system32
        else
             cp $winedir/lib/wine/i386-windows/$dll.dll $WINEPREFIX/drive_c/windows/syswow64
	     if [ ! -d $winedir/lib64 ]
             then
                  cp $winedir/lib/wine/x86_64-windows/$dll.dll $WINEPREFIX/drive_c/windows/system32
             else
                  cp $winedir/lib64/wine/x86_64-windows/$dll.dll $WINEPREFIX/drive_c/windows/system32
             fi
             
        fi
     done
fi


}

if [ "$WINEPREFIX" != "" ]
then 
     copydll
fi
