#!/bin/bash

mesaver=$1
adrenover=$2
type=$3

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

if [ "$type" == "zink" ]
then
     if [ ! -f $cachedir/mesa32-$type-$mesaver.tar.xz ]
     then 
           wget https://github.com/Pipetto-crypto/mesa-builds/raw/master/mesa32-$type-$mesaver.tar.xz -P $cachedir
     fi
     
     if [ ! -f $cachedir/mesa64-$type-$mesaver.tar.xz ]
     then
          wget https://github.com/Pipetto-crypto/mesa-builds/raw/master/mesa64-$type-$mesaver.tar.xz -P $cachedir
     fi
     tar -xvf $cachedir/mesa64-$type-$mesaver.tar.xz -C ~
     tar -xvf $cachedir/mesa32-$type-$mesaver.tar.xz -C ~     

else
     if [ ! -f $cachedir/mesa64-$type-$mesaver-$adrenover.tar.xz ]
     then
          wget https://github.com/Pipetto-crypto/mesa-builds/raw/master/mesa64-$type-$mesaver-$adrenover.tar.xz -P $cachedir
     fi
     
     if [ ! -f $cachedir/mesa32-$type-$mesaver-$adrenover.tar.xz ]
     then
          wget https://github.com/Pipetto-crypto/mesa-builds/raw/master/mesa32-$type-$mesaver-$adrenover.tar.xz -P $cachedir
     fi
     mkdir -p ~/mesa64
     mkdir -p ~/mesa32
     tar -xvf $cachedir/mesa64-$type-$mesaver-$adrenover.tar.xz -C ~/mesa64
     tar -xvf $cachedir/mesa32-$type-$mesaver-$adrenover.tar.xz -C ~/mesa32
fi

