#!/bin/bash

cachedir="$HOME/.local/cache"
mkdir -p $cachedir

apt remove --purge box64-android -y
read -p "Select a stable release, just type the month[e.g. March]: "  MONTH
if [ ! -f $cachedir/box64_0.2.0_"$MONTH"_arm64.deb ]
then
     wget https://github.com/Pipetto-crypto/box86_box64_debs/raw/master/box64debs/box64_0.2.0_"$MONTH"_arm64.deb -P $cachedir
fi
dpkg -i $cachedir/box64_0.2.0_"$MONTH"_arm64.deb
apt-mark hold box64
echo -e "Exit and re-enter to make changes effective"
