#!/bin/bash

apt-mark unhold box86-android:armhf
apt remove --purge box86-android:armhf
apt install box86-android:armhf
echo -e "Whenever you want to update box86 now, you can just do it alongside ubuntu with apt update && apt upgrade command"
