#!/bin/bash

apt remove --purge box86-android:armhf -y
read -p "Select a stable release, just type the month[e.g. March]: "  MONTH
wget https://github.com/Pipetto-crypto/box86_box64_debs/raw/master/box86debs/box86_0.2.8_$MONTH_armhf.deb
dpkg -i *.deb
rm -rf *.deb
apt-mark hold box86-android:armhf
