#!/data/data/com.termux/files/usr/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH

kill $(pidof app_process)

cd $HOME

git clone https://github.com/Pipetto-crypto/androBox.git -b androBoxNew >/dev/null 2>&1
chmod -R a+x ~/androBox/scripts ~/androBox/scripts/WinScripts
rm -rf $PREFIX/glibc/opt/WinScripts && cp -r ~/androBox/scripts/WinScripts $PREFIX/glibc/opt && rm -rf ~/androBox/scripts/WinScripts
rm -rf $PREFIX/glibc/opt/Programs && cp -r ~/androBox/scripts/Programs $PREFIX/glibc/opt && rm -rf ~/androBox/scripts/Programs
rm -rf $PREFIX/glibc/opt/WinStartMenu && cp -r ~/androBox/scripts/WinStartMenu $PREFIX/glibc/opt && rm -rf ~/androBox/scripts/WinStartMenu
mv ~/androBox/scripts/* $PREFIX/bin
rm -rf ~/androBox
pfxupdate
echo "$(git ls-remote --heads https://github.com/Pipetto-crypto/androBox.git | grep refs/heads/androBoxNew | awk '{print $1}')" > /sdcard/androBox/.lastupdated 
