#!/bin/bash

if [ ! "$(id -u)" = "0" ]
then
     echo -e "\nThis program needs to be ran with sudo"
fi

 
wget https://raw.githubusercontent.com/Pipetto-crypto/3in1ProotX86Emus/master/scripts/update-bins
bash update-bins && rm -rf update-bins
