#!/bin/bash

git clone https://github.com/Pipetto-crypto/androBox.git ~/androBox
chmod +x ~/androBox/scripts/*
cp -r ~/androBox/scripts/WinScripts /opt && rm -rf ~/androBox/scripts/WinScripts
cp -r ~/androBox/scripts/Programs /opt && rm -rf ~/androBox/scripts/Programs
cp -r ~/androBox/scripts/WinStartMenu /opt && rm -rf ~/androBox/scripts/WinStartMenu
cp -r ~/androBox/scripts/ProtonStartMenu /opt && rm -rf ~/androBox/scripts/ProtonStartMenu
mv ~/androBox/scripts/* /usr/bin
rm -rf ~/androBox

 
