#!/bin/bash


if [ "$SUDO_USER" != "" ]
then 
     HOME=/home/$SUDO_USER
     USERNAME=$SUDO_USER
else
     USERNAME=root
fi

cachedir="$HOME/.local/cache"
mkdir -p $cachedir
mkdir -p ~/.local/wineprefix
mkdir -p ~/.local/wineprefix64

if [ "$1" == "help" ]
then
     echo -e "Usage: wineswitch version pfxarch"
     echo -e "\nWith no arguments passed it starts interactive mode."
     exit
elif [ "$1" != "" ]
then
     VERSION="$1"
else
     read -p "Select a wine version:" VERSION
fi

if [ "$2" != "" ]
then
     ARCH="$2"
else
     read -p "Select a prefix architecture:" ARCH
fi

if [ ! "$(id -u)" = "0" ]
then
     echo -e "\nThis program needs to be ran with sudo"
     exit
fi

if [ "$ARCH" == "32" ];then CURRARCH="";else CURRARCH="64";fi

if [[ "$VERSION" =~ "ge" ]]
then
     VERSION=$(echo "$VERSION" | tr -d ge) 
     if [ ! -d ~/wine-$VERSION-amd64 ]
     then 
          if [ ! -f $cachedir/wine-lutris-GE-Proton$VERSION-x86_64.tar.xz ]
          then
               wget https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton$VERSION/wine-lutris-GE-Proton$VERSION-x86_64.tar.xz  -P $cachedir
          fi
          tar -xf $cachedir/wine-lutris-GE-Proton$VERSION-x86_64.tar.xz -C ~
          mv ~/lutris-GE-Proton$VERSION-x86_64 ~/wine-$VERSION-amd64
     fi

elif [[ "$VERSION" =~ "custom" ]]
then
     winepath=/sdcard/androBox/wine
     tmpfolder=/tmp/wine
     currentcustomwine=$HOME/.config/currentcustomwine
    
     mkdir -p $tmpfolder && rm -rf $tmpfolder/*
     touch $currentcustomwine

     winefile=$(ls -A $winepath | head )
     extension=${winefile##*.}
    
     if [ ! -d ~/wine-$VERSION-amd64 ] || [ "$winefile" != "$(cat $currentcustomwine)" ] && [ -f "$winepath/$winefile" ]
     then
          echo "$winefile" > $currentcustomwine
          case $extension in
          xz | tar)
              tar --skip-old-files -xf $winepath/$winefile -C $tmpfolder
              ;;
          gz)
              tar --skip-old-files -xzf $winepath/$winefile -C $tmpfolder
              ;;
          zip)
              unzip $winepath/$winefile -d $tmpfolder
              ;;
          esac
     
          binfolder=$(find $tmpfolder -name bin)
          libfolder=$(find $tmpfolder -name lib)
          lib64folder=$(find $tmpfolder -name lib64)
          sharefolder=$(find $tmpfolder -name share)
          mkdir -p ~/wine-$VERSION-amd64
          cp -r $binfolder $libfolder $lib64folder $sharefolder ~/wine-$VERSION-amd64
          rm -rf ~/.local/wineprefix$CURRARCH/wine-$VERSION          
      fi

elif [ "$VERSION" == "proton" ]
then
     protonpath=/sdcard/androBox/proton
     tmpfolder=/tmp/wine
     currentproton=$HOME/.config/currentproton

     mkdir -p $tmpfolder && rm -rf $tmpfolder/*
     touch $currentproton

     protonfile=$(ls -A $protonpath | head )
     extension=${protonfile##*.}
     if [ ! -d ~/proton ] || [ "$protonfile" != "$(cat $currentproton)" ] && [ -f "$protonpath/$protonfile" ]
     then
          echo "$protonfile" > $currentproton
          case $extension in
          xz | tar)
              tar --skip-old-files -xf $protonpath/$protonfile -C $tmpfolder
              ;;
          gz)
              tar --skip-old-files -xzf $protonpath/$protonfile -C $tmpfolder
              ;;
          zip)
              unzip $protonpath/$protonfile -d $tmpfolder
              ;;
          esac
          filesfolder=$(find $tmpfolder -name files)
          protonfolder=$(dirname $filesfolder)
          cp -r $protonfolder ~/proton
          linenumber=$(grep -n ~/proton/proton -e "return subprocess.call(args" | awk '{print $1}' | cut -d":" -f1)
          sed -i "$linenumber"'s/args/["box64"]+args/g' ~/proton/proton
          rm -rf ~/.local/proton-pfx/0
      fi

elif [ ! -d ~/wine-$VERSION-amd64 ]
then
     if (( $(echo "$(echo $VERSION) >= 5.5"|bc -l) ))
     then
          if [ ! -f $cachedir/wine-$VERSION-amd64.tar.xz ]
          then
               wget https://github.com/Kron4ek/Wine-Builds/releases/download/$VERSION/wine-$VERSION-amd64.tar.xz -P $cachedir
          fi
          tar -xf $cachedir/wine-$VERSION-amd64.tar.xz -C ~
     else
          if [ ! -f $cachedir/PlayOnLinux-wine-$VERSION-upstream-linux-amd64.tar.gz ]
          then
               wget https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-amd64/PlayOnLinux-wine-$VERSION-upstream-linux-amd64.tar.gz -P $cachedir
          fi
	  mkdir ~/wine-$VERSION-amd64
	  if file $cachedir/PlayOnLinux-wine-$VERSION-upstream-linux-amd64.tar.gz | grep -q gzip
          then
               tar -xzf $cachedir/PlayOnLinux-wine-$VERSION-upstream-linux-amd64.tar.gz -C ~/wine-$VERSION-amd64
          else
               tar -xf $cachedir/PlayOnLinux-wine-$VERSION-upstream-linux-amd64.tar.gz -C ~/wine-$VERSION-amd64
          fi
     fi 
fi

mkdir -p ~/.config
touch ~/.config/wineconf

if [ "$VERSION" == "proton" ]
then
     [[ ! -d ~/.local/proton-pfx/0/pfx ]] && proton
else
     [[ -z $(awk 'FNR==1' ~/.config/wineconf) ]] && echo "" > ~/.config/wineconf
     [[ -z $(awk 'FNR==2' ~/.config/wineconf) ]] && echo "" >> ~/.config/wineconf
     sed -i "1s/^.*$/$VERSION/" ~/.config/wineconf
     sed -i "2s/^.*$/$ARCH/" ~/.config/wineconf
     [[ ! -d ~/.local/wineprefix$CURRARCH/wine-$VERSION ]] && wine -winedbg winecfg
fi
pfxupdate
