#!/bin/bash


VERSION="$(cat ~/.config/wineconf | awk 'NR==1')"
ARCH="amd64"
CURRARCH="$(cat ~/.config/wineconf | awk 'NR==2')"
WINEARCH=win$CURRARCH
if [ "$CURRARCH" == "32" ];then CURRARCH="";fi
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix$CURRARCH/wine-$VERSION}
DATE=$(date -u +%F@%H-%M-%S)
TERMINAL_LOGFILE=/sdcard/androBox/box_logs/terminal_log@$DATE.txt

log(){

WINEDEBUG="+err"
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$TERMINAL_LOGFILE 2>&1

}


killwine_func(){

env BOX64_PATH=~/wine-$VERSION-$ARCH/bin box64 wineserver -k
pkill -9 -f exe

}


while IFS="" read -r line
do
   if [[ $line  =~ "#" ]]
   then
       continue
   elif [ "$line" != "" ]
   then
       variable=$(echo $line | cut -d"=" -f1)
       [[ ! -v $variable ]] && export "$line"
   fi
done < /sdcard/androBox/box64opts

while IFS="" read -r line
do
   if [[ $line  =~ "#" ]]
   then
       continue
   elif [ "$line" != "" ]
   then
       variable=$(echo $line | cut -d"=" -f1)
       [[ ! -v $variable ]] && export "$line"
   fi
done < /sdcard/androBox/box86opts

touch /tmp/tmpvars.txt

while IFS="" read -r line
do
   if [[ $line  =~ "#" ]]
   then
       continue
   elif [ "$line" != "" ]
   then
       variable=$(echo $line | cut -d"=" -f1)
       [[ ! -v $variable ]] && export "$line"
   fi
done < /sdcard/androBox/uservars

while IFS="" read -r line
do
   if [[ $line  =~ "#" ]]
   then
       continue
   elif [ "$line" != "" ]
   then
       export "$line"
   fi
done < /tmp/tmpvars.txt


index=1
for var in "$@"
do
   if [ -f "$var" ]
   then
        absfile=$(realpath -e "$var")
        argslist[$index]="$absfile"
   elif [ "$var" == "-log" ]
   then 
	log 
   elif [ "$var" == "-winedbg" ]
   then
        WINEDEBUG="+err"
   elif [ "$var" == "-k" ]
   then
        killwine_func
        exit
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done


if [ ! -d ~/wine-$VERSION-$ARCH ]
then
     echo -e "Wine not found"
     exit
fi


if [ -f $WINEPREFIX/islog ] && [ "$(cat $WINEPREFIX/islog)" == "Enabled" ]
then
     log
fi

echo "0" > /tmp/isProton

exec env BOX64_LD_LIBRARY_PATH=~/wine-$VERSION-$ARCH/lib/wine/i386-unix/:~/wine-$VERSION-$ARCH/lib/wine/:~/wine-$VERSION-$ARCH/lib:~/wine-$VERSION-$ARCH/lib/wine/x86_64-unix/:/lib/i386-linux-gnu/:/lib/x86_64-linux-gnu:/lib/aarch64-linux-gnu:/usr/x86_64-linux-gnu/lib \
BOX64_PATH=~/wine-$VERSION-$ARCH/bin \
WINEPREFIX=$WINEPREFIX \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
WINEDEBUG=${WINEDEBUG:=-all} \
WINEARCH=$WINEARCH \
BOX64_RCFILE=/sdcard/androBox/box64.box64rc \
BOX86_RCFILE=/sdcard/androBox/box86.box86rc \
mangohud --dlsym box64 wine$CURRARCH "${argslist[@]}"

