#!/bin/bash

VERSION="$(cat ~/.config/wine64conf | awk 'NR==1')"
ARCH=amd64
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix64/wine-$VERSION}
cp /usr/bin/TFM.exe $WINEPREFIX/drive_c/windows/syswow64
        
if [ ! -f /usr/bin/xrandr ]; then apt install x11-xserver-utils;fi
screenres=$(xrandr | grep current | awk '{print $8$9$10}' | tr -d ,)
ARGS="/desktop=shell,$screenres TFM.exe"

wine64 explorer $ARGS
