#!/bin/bash

VERSION=8-5
ARCH=x86_64
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix64/lutris-GE-Proton$VERSION}

if [ ! -f $WINEPREFIX/drive_c/windows/syswow64/TFM.exe ];then cp /usr/bin/TFM.exe  $WINEPREFIX/drive_c/windows/system32;fi        
if [ ! -f /usr/bin/xrandr ]; then apt install x11-xserver-utils;fi
screenres=$(xrandr | grep current | awk '{print $8$9$10}' | tr -d ,)
ARGS="/desktop=shell,$screenres TFM.exe E:"

env --chdir=$HOME winege $@ explorer $ARGS
