#!/bin/bash

WINEDLLOVERRIDES="services.exe=d"
DATE=$(date -u +%F@%H-%M-%S)
TERMINAL_LOGFILE=/sdcard/3in1ProotX86Emus/box64_logs/terminal_log@$DATE.txt
VERSION="$(cat ~/.config/wine64conf | awk 'NR==1')"
ARCH=amd64


log(){

WINEDEBUG="+err"
echo -e "This wine session will be logged in $TERMINAL_LOGFILE"
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$TERMINAL_LOGFILE 2>&1

}

winetricks_func(){

if [ ! -f /usr/bin/cabextract ];then apt install cabextract;fi
env BOX64_PATH=~/wine-$VERSION-$ARCH/bin:/usr/bin:/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix64/wine-$VERSION} \
box64 winetricks $@

}

killwine_func(){

pkill -9 -f exe

}

index=1
for var in "$@"
do
   if [ -f "$var" ]
   then
        absfile=$(realpath -e "$var")
        argslist[$index]="$absfile"
   elif [ "$var" == "-log" ]
   then
        log
   elif [ "$var" == "-w" ]
   then
        winetricks_func
        exit
   elif [ "$var" == "-nodxvk" ]
   then
        WINEDLLOVERRIDES=""
   elif [ "$var" == "-winedbg" ]
   then
        WINEDEBUG="+err"
   elif [ "$var" == "-k" ]
   then
        killwine_func
        exit
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done

if [ ! -d ~/wine-$VERSION-$ARCH ]
then
     echo -e "Wine not found"
     exit
fi

for line in "$(cat /sdcard/3in1ProotX86Emus/box86opts)"
do
   box86params+=($line)
done

for line in "$(cat /sdcard/3in1ProotX86Emus/box64opts)"
do
   box64params+=($line)
done

WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix64/wine-$VERSION}

if [ -f $WINEPREFIX/islog ] && [ "$(cat $WINEPREFIX/islog)" == "Enabled" ]
then
     log
fi

env ${box86params[@]} ${box64params[@]} BOX64_LD_LIBRARY_PATH=~/wine-$VERSION-$ARCH/lib/wine/i386-unix/:~/wine-$VERSION-$ARCH/lib/wine/:~/wine-$VERSION-$ARCH/lib:~/wine-$VERSION-$ARCH/lib/wine/x86_64-unix/:/lib/i386-linux-gnu/:/lib/x86_64-linux-gnu:/lib/aarch64-linux-gnu:/usr/x86_64-linux-gnu/lib \
BOX64_PATH=~/wine-$VERSION-$ARCH/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix64/wine-$VERSION} \
BOX64_LOG=${BOX64_LOG:-0} \
BOX86_DYNAREC_BIGBLOCK=${BOX86_DYNAREC_BIGBLOCK:-0} \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
WINEDEBUG=${WINEDEBUG:=-all} \
BOX86_DYNAREC_FORWARD=${BOX86_DYNAREC_FORWARD:=0} \
BOX64_DYNAREC_FORWARD=${BOX64_DYNAREC_FORWARD:=0} \
BOX64_RCFILE=${BOX64_RCFILE:=/sdcard/3in1ProotX86Emus/box64rc} \
VK_ICD_FILENAMES="/root/mesa64/freedreno_icd.aarch64.json:/root/mesa32/freedreno_icd.armhf.json" \
box64 wine64 "${argslist[@]}"
