#!/data/data/com.termux/files/usr/bin/bash

unset LD_PRELOAD
unset LD_LIBRARY_PATH

env BOX64_PATH=$PREFIX/glibc/opt/wine/bin \
PATH=$PREFIX/glibc/opt/wine/bin:$PATH \
BOX64_NOERROR=1 \
BOX86_NOERROR=1 \
BOX64_LOG=0 \
BOX64_NOBANNER=1 \
BOX86_NOBANNER=1 \
BOX64_BASH=$HOME/box_bash/bash_x64 \
BOX86_BASH=$HOME/box_bash/bash_x86 \
DISPLAY=:0 \
$PREFIX/glibc/bin/box64 winetricks_x86 $@


