#!/bin/bash

WINEDLLOVERRIDES="$(cat ~/.config/wineconf | awk 'NR==3')"
VERSION="$(cat ~/.config/wineconf | awk 'NR==1')"
ARCH="$(cat ~/.config/wineconf | awk 'NR==2')"
PREFIXARCH=""
DATE=$(date -u +%F@%T)
TERMINAL_LOGFILE=~/box86_logs/terminal_log@$DATE.txt

if [ "$ARCH" == "amd64" ];then PREFIXARCH="64";fi

log(){

WINEDEBUG=+all
echo -e "This wine session will be logged in $TERMINAL_LOGFILE"
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$TERMINAL_LOGFILE 2>&1

}


winetricks_func(){

if [ ! -f /usr/bin/cabextract ];then apt install cabextract;fi
env PATH=$PATH:~/wine-$VERSION-$ARCH/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION} \
box86 winetricks

}

index=1
for var in "$@"
do
   if [ -f "$var" ]
   then
        absfile=$(realpath -e "$var")
        argslist[$index]="$absfile"
   elif [ "$var" == "-log" ]
   then 
	log 
   elif [ "$var" == "-w" ]
   then
        winetricks_func 
        exit
   elif [ "$var" == "-nodxvk" ]
   then
        WINEDLLOVERRIDES=""
   elif [ "$var" == "-winedbg" ]
   then
        WINEDEBUG="default"
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done


if [ ! -d ~/wine-$VERSION-$ARCH ]
then
     echo -e "Wine not found"
     exit
fi

env BOX86_LD_LIBRARY_PATH=~/wine-$VERSION-$ARCH/lib/wine/i386-unix/:~/wine-$VERSION-$ARCH/lib:~/wine-$VERSION-$ARCH/lib/wine:/lib/i386-linux-gnu:/lib/aarch64-linux-gnu/ \
BOX86_PATH=~/wine-$VERSION-$ARCH/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION} \
BOX86_DYNAREC_BIGBLOCK=${BOX86_DYNAREC_BIGBLOCK:-0} \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
WINEDEBUG=${WINEDEBUG:=-all} \
BOX86_DYNAREC_FORWARD=${BOX86_DYNAREC_FORWARD:=0} \
BOX86_RCFILE=${BOX86_RCFILE:=/sdcard/3in1ProotX86Emus/box86rc} \
box86 wine "${argslist[@]}"
