#!/bin/bash
        
if [ ! -f /usr/bin/xrandr ]; then apt install x11-xserver-utils;fi
screenres=$(xrandr | grep current | awk '{print $8$9$10}' | tr -d ,)
ARGS="/desktop=shell,$screenres TFM.exe"

wine64 explorer $ARGS
