#!/bin/bash

VERSION="$(cat ~/.config/wineconf | awk 'NR==1')"
ARCH="$(cat ~/.config/wineconf | awk 'NR==2')"
PREFIXARCH=""
DATE=$(date -u +%F@%H-%M-%S)
TERMINAL_LOGFILE=/sdcard/3in1ProotX86Emus/box86_logs/terminal_log@$DATE.txt

if [ "$ARCH" == "amd64" ];then PREFIXARCH="64";fi

log(){

WINEDEBUG="+err"
echo -e "This wine session will be logged in $TERMINAL_LOGFILE"
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$TERMINAL_LOGFILE 2>&1

}


winetricks_func(){

if [ ! -f /usr/bin/cabextract ];then apt install cabextract;fi
env PATH=$PATH:~/wine-$VERSION-$ARCH/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION} \
box86 winetricks $@

}

killwine_func(){

BOX86_PATH=~/wine-$VERSION-x86/bin WINEPREFIX=$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION box86 wineboot -f
BOX86_PATH=~/wine-$VERSION-x86/bin WINEPREFIX=$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION box86 wineserver -k9
pkill -9 -f exe

}

index=1
for var in "$@"
do
   if [ -f "$var" ]
   then
        absfile=$(realpath -e "$var")
        argslist[$index]="$absfile"
   elif [ "$var" == "-log" ]
   then 
	log 
   elif [ "$var" == "-w" ]
   then
        winetricks_func 
        exit
   elif [ "$var" == "-nodxvk" ]
   then
        WINEDLLOVERRIDES=""
   elif [ "$var" == "-winedbg" ]
   then
        WINEDEBUG="+err"
   elif [ "$var" == "-k" ]
   then
        killwine_func
        exit
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done


if [ ! -d ~/wine-$VERSION-$ARCH ]
then
     echo -e "Wine not found"
     exit
fi

for line in "$(cat /sdcard/3in1ProotX86Emus/box86opts)"
do
   box86params+=($line)
done

WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION}

if [ -f $WINEPREFIX/islog ] && [ "$(cat $WINEPREFIX/islog)" == "Enabled" ]
then
     log
fi

env ${box86params[@]} BOX86_LD_LIBRARY_PATH=~/wine-$VERSION-$ARCH/lib/wine/i386-unix/:~/wine-$VERSION-$ARCH/lib:~/wine-$VERSION-$ARCH/lib/wine:/lib/i386-linux-gnu:/lib/aarch64-linux-gnu/ \
BOX86_PATH=~/wine-$VERSION-$ARCH/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix$PREFIXARCH/wine-$VERSION} \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
WINEDEBUG=${WINEDEBUG:=-all} \
BOX86_RCFILE=${BOX86_RCFILE:=/sdcard/3in1ProotX86Emus/box86rc} \
VK_ICD_FILENAMES="/root/mesa64/freedreno_icd.aarch64.json:/root/mesa32/freedreno_icd.armhf.json" \
box86 wine "${argslist[@]}"
