#!/bin/bash

WINEDLLOVERRIDES="$(cat ~/.config/winegeconf | awk '{NR==1}')"
DATE=$(date -u +%F@%T)
TERMINAL_LOGFILE=~/box64_logs/terminal_log@$DATE.txt
VERSION=8-5
ARCH=x86_64

log(){

WINEDEBUG=+all
echo -e "This wine session will be logged in $TERMINAL_LOGFILE"
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$TERMINAL_LOGFILE 2>&1

}

index=1
for var in "$@"
do
   if [ -f "$var" ]
   then
        absfile=$(realpath -e "$var")
        argslist[$index]="$absfile"
   elif [ "$var" == "-log" ]
   then
        log
   elif [ "$var" == "-nodxvk" ]
   then
        WINEDLLOVERRIDES=""
   elif [ "$var" == "-winedbg" ]
   then
        WINEDEBUG="default"
   else
        argslist[$index]=$var
   fi
   index=$((index+1))
done


if [ ! -d ~/lutris-GE-Proton$VERSION-$ARCH ]
then
     echo -e "WineGE not found"
     exit
fi

BOX64_LD_LIBRARY_PATH=~/lutris-GE-Proton$VERSION-$ARCH/lib/wine/i386-unix/:~/lutris-GE-Proton$VERSION-$ARCH/lib/wine/:~/lutris-GE-Proton$VERSION-$ARCH/lib:~/lutris-GE-Proton$VERSION-$ARCH/lib64/wine/x86_64-unix/:~/lutris-GE-Proton$VERSION-$ARCH/lib64:/lib/i386-linux-gnu/:/lib/x86_64-linux-gnu:/lib/aarch64-linux-gnu:/usr/x86_64-linux-gnu/lib \
BOX64_PATH=~/lutris-GE-Proton$VERSION-$ARCH/bin \
WINEPREFIX=${WINEPREFIX:-$HOME/.local/wineprefix64/lutris-GE-Proton$VERSION} \
BOX64_LOG=${BOX64_LOG:-0} \
BOX86_DYNAREC_BIGBLOCK=${BOX86_DYNAREC_BIGBLOCK:-0} \
WINEDLLOVERRIDES=$WINEDLLOVERRIDES \
WINEDEBUG=${WINEDEBUG:=-all} \
BOX86_DYNAREC_FORWARD=${BOX86_DYNAREC_FORWARD:=0} \
BOX64_DYNAREC_FORWARD=${BOX64_DYNAREC_FORWARD:=0} \
BOX64_RCFILE=${BOX64_RCFILE:=/sdcard/3in1ProotX86Emus/box64rc} \
box64 wine64 "${argslist[@]}"
