#!/bin/bash

export PATH=/data/data/com.termux/files/usr/bin
unset LD_LIBRARY_PATH
WINEPREFIX=${WINEPREFIX:-$HOME/.wine}

cat >> $TMPDIR/tmpvars.txt <<- EOM
BOX86_DYNAREC_FASTNAN=1
BOX86_DYNAREC_FASTROUND=1
BOX86_DYNAREC_STRONGMEM=0
BOX86_DYNAREC_WAIT=0
BOX86_DYNAREC_X87DOUBLE=0
BOX86_MUTEX_ALIGNED=1
BOX64_DYNAREC_FASTNAN=1
BOX64_DYNAREC_FASTROUND=1
BOX64_DYNAREC_STRONGMEM=0
BOX64_DYNAREC_WAIT=0
BOX64_DYNAREC_X87DOUBLE=0
BOX64_MUTEX_ALIGNED=1
EOM
$PREFIX/glibc/opt/WinScripts/restart.sh
